# Generated by Django 3.1.7 on 2021-05-13 13:01

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210509_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products', validators=[api.validators.validate_size, api.validators.validate_extension]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products', validators=[api.validators.validate_size, api.validators.validate_extension]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatars', validators=[api.validators.validate_size, api.validators.validate_extension]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=20),
        ),
        migrations.AlterField(
            model_name='provider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products', validators=[api.validators.validate_size, api.validators.validate_extension]),
        ),
    ]
